# trigger: master
trigger: 
- master

pool: default

steps:
- script: ls
  displayName: 'Print Directory Content'
- script: pwd
  displayName: 'Server Directory Location'
- script: export AUTOMATE_HOSTNAME='anthony-a2.chef-demo.com' && export CHEF_ORG='reesyorg'
  displayName: 'Set Local Variables'
- script: env
  displayName: 'Available Env Variables'
- script: ./policy_push.sh
  displayName: 'Upload Policy to Chef Server'
